#!/bin/bash

PY3=/usr/bin/python3
DIFF=/usr/bin/diff
CAT=/bin/cat

pushd `dirname $0` > /dev/null
PATH=`pwd`
popd > /dev/null

CAP=$PATH/../cap.py

for DIR in $PATH/tests/*; do
    $CAT $DIR/case | $PY3 $CAP > $DIR/b

    $DIFF $DIR/a $DIR/b
    if [ $? -ne 0 ]; then
        echo "出力結果が違います。"
        echo "テストケース: $DIR/case"
        echo "期待する結果: $DIR/a"
        echo "出力された結果: $DIR/b"
        exit 1
    fi
done
