    bin
    / \
  123 bin
      /      \
     if      bin
    /  \     /  \
  comp then 323 nil
   |    |
   1    bin
       / 
     plain 
      |
     223

123
{{ if 1: }}
223
{{ end }}
323

program ::= statement, program

----

program ::= plain | dblock, program

expr ::= ass_expr | pm_expr
ass_expr :: = variable '=' pm_expr
pm_expr ::= md_expr, pm_op pm_expr
pm_op ::= ('+'|'_')
md_expr ::= paren_expr, md_op pm_expr
md_op ::= ('*'|'/')
paren_expr ::= operand | '(' expr ')'
operand ::= number | ababa
ababa ::= variable | caller 
caller ::= caller_name '(' caller_args ')'
caller_args ::= [ operand, ',' ]*
number ::= [ 0-9 ]*
variable ::= [ a-z | A-Z | _ ]* [ 0-9 ]*

statement ::= block_statement | if_statement | for_statement | expr

block_statement ::= '}}' plain_text '{{'

if_statement ::= ('if'|'elif') if_compare ':' code if_else | if_elif
if_compare ::= expr
if_else ::= 'else' '{' code '}'
if_elif ::= if_statement
